# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58188e4737e44022e5834a52aef7f50baa0ec70b2bd885d121948ffcb6a03f3201222af6048924bbdea46171f81238ca81844b81d1e25cea04be18c58f5c25bc

test:
  secret_key_base: 24f0a0b5a8665c4aafc912a6594425081dbc709ab8c38b506fbc1046731042e7ecff7ef686013801853bb1f2d1f00eff280eb8ad3d468e2ab257cad3d1932295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
